version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /recovery/**
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /loggers/**
    schedule:
      interval: monthly
