version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    cooldown:
      default-days: 7
      semver-major-days: 30
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    cooldown:
      default-days: 7
      semver-major-days: 30
    directory: /recovery/**
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    cooldown:
      default-days: 7
      semver-major-days: 30
    directory: /loggers/**
    schedule:
      interval: monthly
