package oops

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"sync"
	"time"

	"github.com/oklog/ulid/v2"
	"github.com/samber/lo"
	"go.opentelemetry.io/otel/trace"
)

/**
 * Functional-options pattern implementation for creating rich error objects.
 *
 * OopsErrorBuilder is an immutable linked list of option closures. Each chainable
 * method returns a new builder whose head closure captures the previous head as
 * "prev". At terminal time (Wrap, New, Errorf, …) a single fresh OopsError is
 * allocated and the chain is traversed once: each closure calls prev first (forward
 * order), then applies its own mutation.
 *
 * This design:
 *   - Costs O(1) per chained call (one closure, no slice copy).
 *   - Never shares mutable map state between two materializations of the same
 *     builder: snap maps are only read (via range), never assigned to e.context.
 *   - Preserves the immutability invariant: branching off a shared base builder
 *     produces independent errors.
 *
 * External API is unchanged.
 *
 * Examples:
 *
 *   // Safe fan-out from a shared base builder:
 *   base := oops.In("service").User("user-123")
 *   err1 := base.With("op", "read").Wrap(readErr)
 *   err2 := base.With("op", "write").Wrap(writeErr)
 */

// optionFunc is one node in the immutable option chain.
// It applies its mutation to e, then forwards to prev (the rest of the chain).
// The next parameter is reserved for external chain composition.
type optionFunc func(e *OopsError, next optionFunc)

// OopsErrorBuilder holds the head of an immutable linked-list option chain.
// Each chainable method returns a new builder without modifying the receiver.
type OopsErrorBuilder struct {
	head optionFunc
}

// newBuilder returns a zero-value OopsErrorBuilder ready for chaining.
func newBuilder() OopsErrorBuilder {
	return OopsErrorBuilder{}
}

// materialize creates a fresh OopsError and runs the full option chain.
func (b OopsErrorBuilder) materialize() OopsError {
	e := OopsError{
		time: time.Now(),
	}
	if b.head != nil {
		b.head(&e, nil)
	}
	return e
}

// Wrap wraps an existing error into an OopsError with the current builder's context.
// If the input error is nil, returns nil.
//
// Example:
//
//	err := oops.
//	  Code("database_error").
//	  In("database").
//	  Wrap(originalError)
func (b OopsErrorBuilder) Wrap(err error) error {
	if err == nil {
		return nil
	}

	o := b.materialize()
	o.err = err
	if o.trace == "" && AutoTraceID {
		o.trace = ulid.Make().String()
		o.traceAutoGenerated = true
	}
	if o.span == "" {
		o.span = ulid.Make().String()
	}
	o.stacktrace = newStacktrace(o.span, (internalFrameDepth-1)+o.callerSkip)
	o.cacheOnce = &sync.Once{}
	o.cacheBlocks = &[]outputBlock{}
	return OopsError(o)
}

// Wrapf wraps an existing error with additional formatted message.
//
// Example:
//
//	err := oops.
//	  Code("database_error").
//	  In("database").
//	  Wrapf(originalError, "failed to execute query: %s", queryName)
func (b OopsErrorBuilder) Wrapf(err error, format string, args ...any) error {
	if err == nil {
		return nil
	}

	o := b.materialize()
	o.err = err
	// Always use fmt.Errorf so that all wrapping verbs (%w, %[1]w, etc.) are
	// handled correctly. The wrapped error object is discarded — only the
	// formatted string is kept; the wrapped error is preserved via o.err.
	o.msg = fmt.Errorf(format, args...).Error()
	if o.trace == "" && AutoTraceID {
		o.trace = ulid.Make().String()
		o.traceAutoGenerated = true
	}
	if o.span == "" {
		o.span = ulid.Make().String()
	}
	o.stacktrace = newStacktrace(o.span, (internalFrameDepth-1)+o.callerSkip)
	o.cacheOnce = &sync.Once{}
	o.cacheBlocks = &[]outputBlock{}
	return OopsError(o)
}

// New creates a new error with the specified message.
//
// Example:
//
//	err := oops.
//	  Code("validation_error").
//	  New("invalid input parameters")
func (b OopsErrorBuilder) New(message string) error {
	o := b.materialize()
	o.err = errors.New(message)
	if o.trace == "" && AutoTraceID {
		o.trace = ulid.Make().String()
		o.traceAutoGenerated = true
	}
	if o.span == "" {
		o.span = ulid.Make().String()
	}
	o.stacktrace = newStacktrace(o.span, (internalFrameDepth-1)+o.callerSkip)
	o.cacheOnce = &sync.Once{}
	o.cacheBlocks = &[]outputBlock{}
	return OopsError(o)
}

// Errorf creates a new error with a formatted message.
//
// Example:
//
//	err := oops.
//	  Code("validation_error").
//	  Errorf("invalid input: expected %s, got %s", expectedType, actualType)
func (b OopsErrorBuilder) Errorf(format string, args ...any) error {
	o := b.materialize()
	o.err = fmt.Errorf(format, args...)
	if o.trace == "" && AutoTraceID {
		o.trace = ulid.Make().String()
		o.traceAutoGenerated = true
	}
	if o.span == "" {
		o.span = ulid.Make().String()
	}
	o.stacktrace = newStacktrace(o.span, (internalFrameDepth-1)+o.callerSkip)
	o.cacheOnce = &sync.Once{}
	o.cacheBlocks = &[]outputBlock{}
	return OopsError(o)
}

// Join combines multiple errors into a single error.
//
// Example:
//
//	err := oops.
//	  Code("multi_error").
//	  Join(err1, err2, err3)
func (b OopsErrorBuilder) Join(e ...error) error {
	return b.Wrap(errors.Join(e...))
}

// Recover handles panics and converts them to OopsError instances.
//
// Example:
//
//	err := oops.
//	  Code("panic_recovered").
//	  Recover(func() { riskyOperation() })
func (b OopsErrorBuilder) Recover(cb func()) (err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = b.Wrap(e)
			} else {
				err = b.Wrap(fmt.Errorf("%v", r))
			}
		}
	}()

	cb()
	return err
}

// Recoverf handles panics with additional context message.
//
// Example:
//
//	err := oops.
//	  Code("panic_recovered").
//	  Recoverf(func() { riskyOperation() }, "panic in operation: %s", operationName)
func (b OopsErrorBuilder) Recoverf(cb func(), msg string, args ...any) (err error) {
	return b.Wrapf(b.Recover(cb), msg, args...)
}

// Assert panics if the condition is false.
//
// Example:
//
//	oops.
//	  Code("assertion_failed").
//	  Assert(userID != "")
func (b OopsErrorBuilder) Assert(condition bool) OopsErrorBuilder {
	if !condition {
		panic(b.Errorf("assertion failed"))
	}

	return b
}

// Assertf panics if the condition is false with a custom message.
//
// Example:
//
//	oops.
//	  Code("assertion_failed").
//	  Assertf(userID != "", "user ID cannot be empty, got: %s", userID)
func (b OopsErrorBuilder) Assertf(condition bool, msg string, args ...any) OopsErrorBuilder {
	if !condition {
		panic(b.Errorf(msg, args...))
	}

	return b
}

// Code sets a machine-readable error code or slug.
func (b OopsErrorBuilder) Code(code any) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.code = code
	}}
}

// Time sets the timestamp when the error occurred.
func (b OopsErrorBuilder) Time(t time.Time) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.time = t
	}}
}

// Since calculates the duration since the specified time.
func (b OopsErrorBuilder) Since(t time.Time) OopsErrorBuilder {
	d := time.Since(t)
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.duration = d
	}}
}

// Duration sets the duration associated with the error.
func (b OopsErrorBuilder) Duration(duration time.Duration) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.duration = duration
	}}
}

// In sets the domain or feature category for the error.
func (b OopsErrorBuilder) In(domain string) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.domain = domain
	}}
}

// Tags adds multiple tags for categorizing the error.
func (b OopsErrorBuilder) Tags(tags ...string) OopsErrorBuilder {
	// tags is a fresh slice from varargs — safe to capture directly.
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.tags = append(e.tags, tags...)
	}}
}

// With adds key-value pairs to the error context.
//
// Example:
//
//	oops.With("user_id", 123, "operation", "create").Errorf("validation failed")
func (b OopsErrorBuilder) With(kv ...any) OopsErrorBuilder {
	// Parse and snapshot at call time so later mutations to kv don't affect us.
	snap := make(map[string]any, len(kv)/2)
	for i := 0; i+1 < len(kv); i += 2 {
		if key, ok := kv[i].(string); ok {
			snap[key] = kv[i+1]
		}
	}
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		// Always merge (never direct-assign snap) so each materialization gets
		// its own e.context and snap remains read-only across multiple Wrap calls.
		if e.context == nil {
			e.context = make(map[string]any, len(snap))
		}
		for k, v := range snap {
			e.context[k] = v
		}
	}}
}

// WithContext extracts values from a Go context and adds them to the error context.
//
// Example:
//
//	oops.WithContext(ctx, "request_id", "user_id").Errorf("operation failed")
func (b OopsErrorBuilder) WithContext(ctx context.Context, keys ...any) OopsErrorBuilder {
	// Resolve all values and the OTel span at call time — context is immutable.
	snap := make(map[string]any, len(keys))
	for _, k := range keys {
		switch k := k.(type) {
		case fmt.Stringer:
			snap[k.String()] = contextValueOrNil(ctx, k.String())
		case string:
			snap[k] = contextValueOrNil(ctx, k)
		case *string:
			snap[*k] = contextValueOrNil(ctx, *k)
		default:
			snap[fmt.Sprint(k)] = contextValueOrNil(ctx, k)
		}
	}

	var otelTrace, otelSpan string
	spanCtx := trace.SpanContextFromContext(ctx)
	if spanCtx.HasTraceID() {
		otelTrace = spanCtx.TraceID().String()
	}
	if spanCtx.HasSpanID() {
		otelSpan = spanCtx.SpanID().String()
	}

	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		if e.context == nil {
			e.context = make(map[string]any, len(snap))
		}
		for k, v := range snap {
			e.context[k] = v
		}
		if otelTrace != "" {
			e.trace = otelTrace
		}
		if otelSpan != "" {
			e.span = otelSpan
		}
	}}
}

// Trace sets a transaction, trace, or correlation ID.
func (b OopsErrorBuilder) Trace(traceID string) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.trace = traceID
	}}
}

// Span sets the current span identifier.
func (b OopsErrorBuilder) Span(span string) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.span = span
	}}
}

// Hint provides a debugging hint for resolving the error.
func (b OopsErrorBuilder) Hint(hint string) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.hint = hint
	}}
}

// Public sets a user-safe error message.
func (b OopsErrorBuilder) Public(public string) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.public = public
	}}
}

// Owner sets the person or team responsible for handling this error.
func (b OopsErrorBuilder) Owner(owner string) OopsErrorBuilder {
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.owner = owner
	}}
}

// User adds user information to the error context.
//
// Example:
//
//	oops.User("user-123", "firstname", "John", "lastname", "Doe").Errorf("permission denied")
func (b OopsErrorBuilder) User(userID string, userData ...any) OopsErrorBuilder {
	snap := identityArgsToMap(userData)
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.userID = userID
		// Always merge (never direct-assign snap) to keep snap read-only.
		if e.userData == nil {
			e.userData = make(map[string]any, len(snap))
		}
		for k, v := range snap {
			e.userData[k] = v
		}
	}}
}

// Tenant adds tenant information to the error context.
//
// Example:
//
//	oops.Tenant("tenant-456", "name", "Acme Corp", "plan", "premium").Errorf("quota exceeded")
func (b OopsErrorBuilder) Tenant(tenantID string, tenantData ...any) OopsErrorBuilder {
	snap := identityArgsToMap(tenantData)
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.tenantID = tenantID
		// Always merge (never direct-assign snap) to keep snap read-only.
		if e.tenantData == nil {
			e.tenantData = make(map[string]any, len(snap))
		}
		for k, v := range snap {
			e.tenantData[k] = v
		}
	}}
}

const badKey = "!BADKEY"

// identityArgsToMap converts variadic user/tenant arguments into a flat map.
//
// Supported inputs:
//   - slog.Attr values
//   - map[string]any values
//   - alternating string key/value pairs
//
// Malformed values are stored under "!BADKEY", mirroring log/slog argsToAttr.
func identityArgsToMap(args []any) map[string]any {
	payload := map[string]any{}

	for len(args) > 0 {
		switch value := args[0].(type) {
		case slog.Attr:
			payload[value.Key] = slogValueToAny(value.Value, 0)
			args = args[1:]
		case map[string]any:
			for key, mapValue := range value {
				payload[key] = mapValue
			}
			args = args[1:]
		case string:
			if len(args) == 1 {
				payload[badKey] = value
				return payload
			}

			payload[value] = args[1]
			args = args[2:]
		default:
			payload[badKey] = value
			args = args[1:]
		}
	}

	return payload
}

// slogValueToAny converts a slog.Value into its resolved Go representation.
//
// Group values are converted recursively into map[string]any so they can be
// stored in user/tenant payload maps.
//
// The depth parameter guards against circular slog.LogValuer chains.
// Returns nil when depth exceeds 10.
func slogValueToAny(value slog.Value, depth int) any {
	value = value.Resolve()

	switch value.Kind() {
	case slog.KindString:
		return value.String()
	case slog.KindInt64:
		return value.Int64()
	case slog.KindUint64:
		return value.Uint64()
	case slog.KindFloat64:
		return value.Float64()
	case slog.KindBool:
		return value.Bool()
	case slog.KindDuration:
		return value.Duration()
	case slog.KindTime:
		return value.Time()
	case slog.KindGroup:
		group := map[string]any{}
		for _, attr := range value.Group() {
			group[attr.Key] = slogValueToAny(attr.Value, depth+1)
		}
		return group
	case slog.KindLogValuer:
		if depth > 10 {
			return nil
		}
		return slogValueToAny(value.LogValuer().LogValue(), depth+1)
	case slog.KindAny:
		return value.Any()
	default:
		return value.Any()
	}
}

// CallerSkip sets the number of additional callers to skip when capturing
// the stack trace.
func (b OopsErrorBuilder) CallerSkip(skip int) OopsErrorBuilder {
	if skip < 0 {
		skip = 0
	}
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.callerSkip = skip
	}}
}

// Request adds HTTP request information to the error context.
//
// Example:
//
//	oops.Request(req, true).Errorf("request processing failed")
func (b OopsErrorBuilder) Request(req *http.Request, withBody bool) OopsErrorBuilder {
	ptr := lo.ToPtr(lo.T2(req, withBody))
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.req = ptr
	}}
}

// Response adds HTTP response information to the error context.
//
// Example:
//
//	oops.Response(res, false).Errorf("response processing failed")
//
//nolint:bodyclose
func (b OopsErrorBuilder) Response(res *http.Response, withBody bool) OopsErrorBuilder {
	ptr := lo.ToPtr(lo.T2(res, withBody))
	prev := b.head
	return OopsErrorBuilder{head: func(e *OopsError, next optionFunc) {
		if prev != nil {
			prev(e, next)
		} else if next != nil {
			next(e, nil)
		}
		e.res = ptr
	}}
}
